channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=25.1.1
- pip:
  - mlflow==2.7.0
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.2
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.3.0
  - scipy==1.16.0
name: mlflow-env
